version: "3.8"

services:
  # TODO: 1. SQL
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/data/postgres"
    volumes:
      - db_data/:/var/lib/postgresql/data/postgres:ro
      - ./database/migration/init:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_MAPPING}:${POSTGRES_PORT}"
    networks:
      - service_banking-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  db_data:
    driver: local

networks:
  service_banking-network:
    driver: bridge
